# Kafka Cluster and Topic Resources
# Apply this after Strimzi operator is running and CRDs are available

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka-demo
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    listeners:
    - name: oauth
      port: 9092
      type: internal
      tls: false
      authentication:
        type: oauth
        validIssuerUri: http://192.168.49.2:30080/realms/kafka
        jwksEndpointUri: http://192.168.49.2:30080/realms/kafka/protocol/openid-connect/certs
        userNameClaim: preferred_username
        clientId: kafka
        clientSecret:
          secretName: kafka-oauth-secret
          key: "GUidNNO1ON3B9J2KgXMh7tedX8q3GUPS"
        checkAccessTokenType: false
    - name: external
      port: 9094
      type: nodeport
      tls: false
      authentication:
        type: oauth
        validIssuerUri: http://192.168.49.2:30080/realms/kafka
        jwksEndpointUri: http://192.168.49.2:30080/realms/kafka/protocol/openid-connect/certs
        userNameClaim: preferred_username
        clientId: kafka
        clientSecret:
          secretName: kafka-oauth-secret
          key: "GUidNNO1ON3B9J2KgXMh7tedX8q3GUPS"
        checkAccessTokenType: false
      configuration:
        bootstrap:
          nodePort: 30092
    authorization:
      type: keycloak
      clientId: kafka
      tokenEndpointUri: http://keycloak-service.kafka-demo.svc.cluster.local:8080/realms/kafka/protocol/openid-connect/token
      delegateToKafkaAcls: false
      grantsRefreshPeriodSeconds: 60
      grantsRefreshPoolSize: 5
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
    resources:
      requests:
        memory: 1Gi
        cpu: "0.5"
      limits:
        memory: 2Gi
        cpu: "1"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    resources:
      requests:
        memory: 256Mi
        cpu: "0.1"
      limits:
        memory: 512Mi
        cpu: "0.25"
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: demo-topic
  namespace: kafka-demo
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.ms: 3600000